pure_pursuit_node:
  ros__parameters:
    waypoints_path: "/home/go86bel/f1tumth/src/f1tenth_ws_waterloo/src/pure_pursuit/racelines/traj_race_cl-2024-05-29 12:17:03.515967.csv" 
    odom_topic: "/ego_racecar/odom"
    car_refFrame: "ego_racecar/base_link"
    global_refFrame: "map"
    drive_topic: "/drive"
    rviz_waypointselected_topic: "/waypoint_selected"
    
    # Pure Pursuit Parameters
    max_lookeahead: 1.0
    K_p: 0.5
    steering_limit: 25.0
    velocity_percentage: 1.0


waypoint_visualiser_node:
  ros__parameters:
    waypoints_path: "/home/go86bel/f1tumth/src/f1tenth_ws_waterloo/src/pure_pursuit/racelines/traj_race_cl-2024-05-29 12:17:03.515967.csv" 
