rrt:
  ros__parameters:
    waypoints_path: "/home/go86bel/f1tumth/src/f1tenth_ws_waterloo/src/rrt/racelines/e7_floor5.csv" 
    odom_topic:  "/ego_racecar/odom"
    segments: 512
    velocity_min: 1.5
    velocity_max: 6.0
    cells_per_meter: 10
    lookahead_distance: 3.0
    is_sim: True
